// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuqxqdnbjihnxrqabmdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1cXhxZG5iamlobnhycWFibWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjY0NzIsImV4cCI6MjA3MzYwMjQ3Mn0.puIEnly1eP64A5kbUzxwXgir-8_LeeN05kD4XMF9yY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});